apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-mis-deployment
  labels:
    app: student-mis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-mis
  template:
    metadata:
      labels:
        app: student-mis
    spec:
      containers:
      - name: student-mis-app
        image: student-mis-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: student-mis-service
spec:
  selector:
    app: student-mis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer